properties:
    - key : 'server.apppath'
      value : '/sco-server/api/v1'
    - key : 'server.url'
      value : 'http://cds-swg1.cims.nyu.edu'
    - key : 'server.port'
      value : 5000
    - key : 'server.datadir'
      value : './resources/data'
    - key : 'server.logfile'
      value : './resources/scoserv.log'
    - key : 'mongo.db'
      value : 'scosrv'
    - key : 'app.name'
      value : 'Standard Cortical Observer - Web API'
    - key : 'app.title'
      value : 'Standard Cortical Observer'
    - key: 'app.debug'
      value: true
    - key : 'home.title'
      value : 'Welcome'
    - key: home.content
      value: 'https://raw.githubusercontent.com/heikomuller/sco-server/master/config/homepage.html.txt'
